### ISSUE TITLE
运行过程中断开，显示内存什么的问题，麻烦作者看看！！

### ISSUE THREAD

**Issue by Qa7060123** [donwa/gclone#35]
运行过程中断开，显示内存什么的问题，麻烦作者看看！！

错误代码：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xbefe2d]

goroutine 44 [running]:
github.com/donwa/gclone/backend/drive.(*Fs).Copy.func1(0x19fc4a0, 0xc000a9b880, 0x6eb267ef)
        /home/runner/work/gclone/gclone/backend/drive/drive.go:2182 +0x6d
github.com/rclone/rclone/fs.pacerInvoker(0x2, 0xa, 0xc000b29080, 0xc000a9b880, 0x19fc4a0, 0xc000a9b880)
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/fs.go:1417 +0x3c
github.com/rclone/rclone/lib/pacer.(*Pacer).call(0xc000463380, 0xc000b29080, 0xa, 0x30, 0x15cd520)
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/lib/pacer/pacer.go:197 +0x8b
github.com/rclone/rclone/lib/pacer.(*Pacer).Call(0xc000463380, 0xc000b29080, 0xc000614ac0, 0xc0001f70e0)
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/lib/pacer/pacer.go:216 +0x6a
github.com/donwa/gclone/backend/drive.(*Fs).Copy(0xc0002516c0, 0x1a269c0, 0xc000614ac0, 0x1a3dd20, 0xc0006f1080, 0xc0001f70e0, 0x41, 0xbfb0ff4df0f79c73, 0x32b789228, 0x243bcc0, ...)
        /home/runner/work/gclone/gclone/backend/drive/drive.go:2181 +0x2f2
github.com/rclone/rclone/fs/operations.Copy(0x1a269c0, 0xc000614ac0, 0x1a3dca0, 0xc0002516c0, 0x0, 0x0, 0xc0001f70e0, 0x41, 0x1a3dd20, 0xc0006f1080, ...)
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/operations/operations.go:365 +0x2ad
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc00003c8c0, 0x1a269c0, 0xc000614ac0, 0xc0001979a0, 0x1a3dca0, 0xc0002516c0, 0xc00003c998)
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/sync/sync.go:331 +0x21c
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/sync/sync.go:356 +0xb1

**Comment by ghosthim** [comment]
看这。 #16

**Comment by Ruke805** [comment]
How to fix it? I have the same problem

**Comment by Xm798** [comment]
> How to fix it? I have the same problem

https://github.com/donwa/gclone/issues/16
