### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by MissSarahh** [donwa/gclone#5]
I am facing this error. 
````gclone sa file: /content/mnrmfc/accounts47.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xbefe2d]

goroutine 48 [running]:
github.com/donwa/gclone/backend/drive.(*Fs).Copy.func1(0x19fc4a0, 0xc0002da170, 0x6a751e76)
	/home/runner/work/gclone/gclone/backend/drive/drive.go:2182 +0x6d
github.com/rclone/rclone/fs.pacerInvoker(0x2, 0xa, 0xc000776270, 0xc0002da170, 0x19fc4a0, 0xc0002da170)
	/home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/fs.go:1417 +0x3c
github.com/rclone/rclone/lib/pacer.(*Pacer).call(0xc0001e3620, 0xc000776270, 0xa, 0x30, 0x15cd520)
	/home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/lib/pacer/pacer.go:197 +0x8b
github.com/rclone/rclone/lib/pacer.(*Pacer).Call(0xc0001e3620, 0xc000776270, 0xc000706780, 0xc00011cfc0)
	/home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/lib/pacer/pacer.go:216 +0x6a
github.com/donwa/gclone/backend/drive.(*Fs).Copy(0xc00063cc40, 0x1a269c0, 0xc000706780, 0x1a3dd20, 0xc0000ff580, 0xc00011cfc0, 0x64, 0xbf8ac8dc14841245, 0x49d7eedd, 0x243bcc0, ...)
	/home/runner/work/gclone/gclone/backend/drive/drive.go:2181 +0x2f2
github.com/rclone/rclone/fs/operations.Copy(0x1a269c0, 0xc000706780, 0x1a3dca0, 0xc00063cc40, 0x0, 0x0, 0xc00011cfc0, 0x64, 0x1a3dd20, 0xc0000ff580, ...)
	/home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/operations/operations.go:365 +0x2ad
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc0007408c0, 0x1a269c0, 0xc000706780, 0xc000273360, 0x1a3dca0, 0xc00063cc40, 0xc000740998)
	/home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/sync/sync.go:331 +0x21c
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers
	/home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/sync/sync.go:356 +0xb1
````
What's the reason? Am i doing something wrong?
Copy starts and throws this error

**Comment by justcopy** [comment]
check your config file. it may lack “/” at the end of sa folder.

**Comment by MissSarahh** [comment]
> check your config file. it may lack “/” at the end of sa folder.

Thank You. Its working now. Much Love
