### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by anlo1220** [donwa/gclone#57]
![image](https://user-images.githubusercontent.com/61088753/161243711-94f2e729-c33a-4a81-a59e-90152a19d638.png)

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6e5552]

goroutine 47 [running]:
net/http.(*Client).deadline(0x0, 0x16ce4df, 0x11, 0xc0009b3168)
        /opt/hostedtoolcache/go/1.13.8/x64/src/net/http/client.go:187 +0x22
net/http.(*Client).do(0x0, 0xc000a26300, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.8/x64/src/net/http/client.go:527 +0x22c
net/http.(*Client).Do(...)
        /opt/hostedtoolcache/go/1.13.8/x64/src/net/http/client.go:509
github.com/donwa/gclone/backend/drive.(*Fs).Upload.func1(0x19fc400, 0x0, 0x0)
        /home/runner/work/gclone/gclone/backend/drive/upload.go:93 +0x55a
github.com/rclone/rclone/fs.pacerInvoker(0x2, 0xa, 0xc0007be000, 0xc0006177d0, 0x19fc4a0, 0xc0006177d0)
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/fs.go:1417 +0x3c
github.com/rclone/rclone/lib/pacer.(*Pacer).call(0xc0000c2300, 0xc0007be000, 0xa, 0x80, 0x164f460)
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/lib/pacer/pacer.go:197 +0x8b
github.com/rclone/rclone/lib/pacer.(*Pacer).Call(0xc0000c2300, 0xc0007be000, 0x30, 0x16bbca1)
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/lib/pacer/pacer.go:216 +0x6a
github.com/donwa/gclone/backend/drive.(*Fs).Upload(0xc00025e1c0, 0x1a269c0, 0xc000394180, 0x19f8d60, 0xc00081c9c0, 0x529572ce, 0x16c3e52, 0x9, 0x0, 0x0, ...)
        /home/runner/work/gclone/gclone/backend/drive/upload.go:73 +0x529
github.com/donwa/gclone/backend/drive.(*Fs).PutUnchecked(0xc00025e1c0, 0x1a269c0, 0xc000394180, 0x19f8d60, 0xc00081c9c0, 0x7fea7fe02ac0, 0xc0007a0de0, 0xc0006165b0, 0x1, 0x1, ...)
        /home/runner/work/gclone/gclone/backend/drive/drive.go:2007 +0x35e
github.com/donwa/gclone/backend/drive.(*Fs).Put(0xc00025e1c0, 0x1a269c0, 0xc000394180, 0x19f8d60, 0xc00081c9c0, 0x7fea7fe02ac0, 0xc0007a0de0, 0xc0006165b0, 0x1, 0x1, ...)
        /home/runner/work/gclone/gclone/backend/drive/drive.go:1939 +0x19c
github.com/rclone/rclone/fs/operations.Copy(0x1a269c0, 0xc000394180, 0x1a3dca0, 0xc00025e1c0, 0x0, 0x0, 0xc000671110, 0xc1, 0x1a3eea0, 0xc0007a0de0, ...)
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/operations/operations.go:425 +0x152c
github.com/rclone/rclone/fs/operations.Move(0x1a269c0, 0xc000394180, 0x1a3dca0, 0xc00025e1c0, 0x0, 0x0, 0xc000671110, 0xc1, 0x1a3eea0, 0xc0007a0de0, ...)
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/operations/operations.go:540 +0x42a
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc00025e700, 0x1a269c0, 0xc000394180, 0xc0005d0190, 0x1a3dca0, 0xc00025e1c0, 0xc00025e7d8)
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/sync/sync.go:329 +0x189
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/sync/sync.go:356 +0xb1

**Comment by anlo1220** [comment]
service_account_file_path = /root/accounts/

/root/accounts need "/" >>>> /root/accounts/
